##
## -- DIESE DATEI NICHT BEARBEITEN --
##
## Die Datei '.env' für die Konfiguration bearbeiten.
## 
##

services:
  skeleton_3.11:
    container_name: skeleton_3.11
    user: "${USE_UID}:${USE_GID}"
    build: .
    command: python ./skeleton.py
    network_mode: "host"
    volumes:
      - .:/skeleton 
